version: "3"

services:

  parser:
    build: .
    depends_on:
      - db
    environment:
      POSTGRES_DB: "cameras"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgreSQL123"

  db:
    image: mdillon/postgis:latest
    restart: always
    environment:
      POSTGRES_DB: "cameras"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgreSQL123"
    ports:
      - 5436:5432
